apiVersion: v1
kind: ConfigMap
metadata:
  name: tcp-services
#  namespace: ingress-nginx
data:
  9000: "default/tryk:9000"
---
apiVersion: networking.k8s.io/v1beta1 # for versions before 1.14 use extensions/v1beta1
kind: Ingress
metadata:
  name: tryk-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
  - host: tryk.info
    http:
      paths:
      - path: /
        backend:
          serviceName: tryk
          servicePort: 9000
---
apiVersion: v1
kind: Service
metadata:
  name: tryk
  labels:
    run: tryk
spec:
  ports:
  - port: 9000
    protocol: TCP
  selector:
    run: tryk
---
apiVersion: v1
binaryData:
  node1.key: CAESQOTbKTslo4CVafalT/2LiYjzXl4EHalsI4Wo4QAETv0Cx+l1m1VvZ5Il9NAGODI1skrH1rhh7ZSAdYo+sfixIxA=
kind: ConfigMap
metadata:
  name: tryk-node-key
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tryk
spec:
  selector:
    matchLabels:
      run: tryk
  replicas: 1
  template:
    metadata:
      labels:
        run: tryk
    spec:
      containers:
      - name: tryk
        image:  owainperry/tryk:0.2
        command: ["/tryk"]
        args:
        - "-sp"
        - "9000"
        - "-n"
        - "node1"
        ports:
        - containerPort: 9000
        volumeMounts:
        - name: key-volume
          mountPath: /node1.key
          subPath: node1.key
      volumes:
        - name: key-volume
          configMap:
            name: tryk-node-key

